"""empty message

Revision ID: 3a7fe62f7ba2
Revises: 56c4ab125e88
Create Date: 2020-01-17 11:33:10.021926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7fe62f7ba2'
down_revision = '56c4ab125e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('readonly', sa.Boolean(), nullable=True))
    op.add_column('text_field', sa.Column('bind_parameter', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_field', 'bind_parameter')
    op.drop_column('field', 'readonly')
    # ### end Alembic commands ###
