"""empty message

Revision ID: 56c4ab125e88
Revises: b35646c6b416
Create Date: 2020-01-16 12:34:03.651784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c4ab125e88'
down_revision = 'b35646c6b416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_field', sa.Column('from_wechat', sa.Boolean(), nullable=True))
    op.add_column('text_field', sa.Column('vertify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_field', 'vertify')
    op.drop_column('text_field', 'from_wechat')
    # ### end Alembic commands ###
