"""empty message

Revision ID: 5bd1b4fa3e0a
Revises: 
Create Date: 2019-12-17 23:20:50.012132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd1b4fa3e0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('discriminator', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('select_field',
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_field',
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placeholder', sa.String(length=1000), nullable=True),
    sa.Column('default', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['select_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    op.drop_table('text_field')
    op.drop_table('select_field')
    op.drop_table('field')
    op.drop_table('form')
    # ### end Alembic commands ###
