"""empty message

Revision ID: 5e605b10cd96
Revises: 3493f6fb2960
Create Date: 2020-03-02 07:10:52.439846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e605b10cd96'
down_revision = '3493f6fb2960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('form_id_index', table_name='choice')
    op.add_column('constraint', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.alter_column('max_constraint', column_name='min', new_column_name='max', existing_type=sa.Integer)

    op.add_column('field', sa.Column('error_message', sa.String(length=255), nullable=True))
    op.add_column('field', sa.Column('error_message_enabled', sa.Boolean(), nullable=True, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constraint', 'enabled')
    op.drop_column('field', 'error_message')
    op.drop_column('field', 'error_message_enabled')

    op.alter_column('max_constraint', column_name='max', new_column_name='min', existing_type=sa.Integer)
    # op.create_index('form_id_index', 'choice', ['form_id'], unique=False)
    # ### end Alembic commands ###
