"""empty message

Revision ID: 6b710a06ab76
Revises: 365074921fc6
Create Date: 2020-02-26 21:18:26.597245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b710a06ab76'
down_revision = '365074921fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.add_column('field', sa.Column('error_message_enabled', sa.Boolean(), nullable=True))

    op.add_column('option', sa.Column('checked', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field', 'error_message_enabled')
    op.drop_column('field', 'error_message')

    op.drop_column('option', 'checked')
    # ### end Alembic commands ###
