"""empty message

Revision ID: 7ed08084e2ce
Revises: 
Create Date: 2019-12-31 17:01:38.125345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed08084e2ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('value_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('value',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('ua_browser', sa.String(length=100), nullable=True),
    sa.Column('ua_browser_version', sa.String(length=10), nullable=True),
    sa.Column('ua_os', sa.String(length=100), nullable=True),
    sa.Column('ua_os_version', sa.String(length=10), nullable=True),
    sa.Column('ua_device', sa.String(length=50), nullable=True),
    sa.Column('ua_device_brand', sa.String(length=50), nullable=True),
    sa.Column('ua_device_model', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('discriminator', sa.String(length=50), nullable=True),
    sa.Column('layout_row_index', sa.Integer(), nullable=True),
    sa.Column('layout_column_index', sa.Integer(), nullable=True),
    sa.Column('layout_columns', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constraint',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('discriminator', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('select_field',
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('option_sequence', sa.Integer(), nullable=True),
    sa.Column('default', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_field',
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placeholder', sa.String(length=1000), nullable=True),
    sa.Column('default', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('max_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['constraint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('min_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['constraint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['select_field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('range_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['constraint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_constraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['constraint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('required_constraint')
    op.drop_table('range_constraint')
    op.drop_table('option')
    op.drop_table('min_constraint')
    op.drop_table('max_constraint')
    op.drop_table('text_field')
    op.drop_table('select_field')
    op.drop_table('constraint')
    op.drop_table('field')
    op.drop_table('value')
    op.drop_table('form')
    # ### end Alembic commands ###
