"""empty message

Revision ID: 8aa5c22b9767
Revises: 5e605b10cd96
Create Date: 2020-03-16 14:49:59.719998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa5c22b9767'
down_revision = '5e605b10cd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('form_id_index', table_name='choice')
    op.add_column('option', sa.Column('checked', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'checked')
    op.create_index('form_id_index', 'choice', ['form_id'], unique=False)
    # ### end Alembic commands ###
