"""empty message

Revision ID: ae9b80d9db26
Revises: 7ed08084e2ce
Create Date: 2020-01-03 11:22:28.242592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9b80d9db26'
down_revision = '7ed08084e2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('form', sa.Column('record_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'record_count')
    op.drop_column('form', 'published_at')
    # ### end Alembic commands ###
