"""empty message

Revision ID: b35646c6b416
Revises: ae9b80d9db26
Create Date: 2020-01-06 23:00:15.685552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35646c6b416'
down_revision = 'ae9b80d9db26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('ua_browser', sa.String(length=100), nullable=True),
    sa.Column('ua_browser_version', sa.String(length=10), nullable=True),
    sa.Column('ua_os', sa.String(length=100), nullable=True),
    sa.Column('ua_os_version', sa.String(length=10), nullable=True),
    sa.Column('ua_device', sa.String(length=50), nullable=True),
    sa.Column('ua_device_brand', sa.String(length=50), nullable=True),
    sa.Column('ua_device_model', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
