"""empty message

Revision ID: cec63688b694
Revises: 9ba7c1863ed2
Create Date: 2019-12-29 00:27:41.361343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec63688b694'
down_revision = '9ba7c1863ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('form', sa.Column('value_sequence', sa.Integer(), nullable=True))
    op.add_column('form', sa.Column('version', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'form', 'ab_user', ['user_id'], ['id'])
    op.add_column('value', sa.Column('sequence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('value', 'sequence')
    op.drop_constraint(None, 'form', type_='foreignkey')
    op.drop_column('form', 'version')
    op.drop_column('form', 'value_sequence')
    op.drop_column('form', 'user_id')
    # ### end Alembic commands ###
