"""empty message

Revision ID: e678d1081ac2
Revises: dbeffe906094
Create Date: 2020-02-19 16:48:35.135113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e678d1081ac2'
down_revision = 'dbeffe906094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'description')
    # ### end Alembic commands ###
